id: P010454
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10155
  title: རྩོད་སྒྲུབ་རིག་པའི་སྤྱི་དོན་གོ་བདེར་བརྗོད་པ།
  author: ''
  volumes:
    a60e4782cfdd4291bdc30970702795b0:
      image_group_id: I1KG10158
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
