id: P010454
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:42.465230
source_metadata:
  id: bdr:W1KG10155
  title: རྩོད་སྒྲུབ་རིག་པའི་སྤྱི་དོན་གོ་བདེར་བརྗོད་པ།
  author: ''
  volumes:
    a60e4782cfdd4291bdc30970702795b0:
      image_group_id: I1KG10158
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
