id: I1CBF6CF5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T15:14:22+00:00'
last_modified: '2022-06-08T13:43:32.744433+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10155
  title: རྩོད་སྒྲུབ་རིག་པའི་སྤྱི་དོན་གོ་བདེར་བརྗོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BB40:
      image_group_id: I1KG10158
      title: ''
      total_pages: 268
      order: 1
      base_file: BB40.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
